#!/bin/bash

#Store the current working directory in a variable
CURRENT_DIR=$(pwd)

#Change to the previous directory
cd -

#Print the current working directory
echo "Change to: $(pwd)"

#Change back to the original working directory
cd "$CURRENT_DIR"
